spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:github_files_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    # Tras crear el esquema con Hibernate, ejecutar data.sql (datos demo).
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8084}

logging:
  level:
    root: INFO
    com.githubx.githubfilesms: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
