/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.smithy.g.files.server.files.api;

import com.smithy.g.files.server.files.model.BadRequestErrorResponseContent;
import java.math.BigDecimal;
import com.smithy.g.files.server.files.model.CompareDTO;
import com.smithy.g.files.server.files.model.ConflictErrorResponseContent;
import com.smithy.g.files.server.files.model.CreateFileBody;
import com.smithy.g.files.server.files.model.CreateFolderBody;
import com.smithy.g.files.server.files.model.DeleteFileResponseBody;
import com.smithy.g.files.server.files.model.FileOperationResponse;
import com.smithy.g.files.server.files.model.ForbiddenErrorResponseContent;
import com.smithy.g.files.server.files.model.GetCommitBody;
import com.smithy.g.files.server.files.model.GetFileContentBody;
import com.smithy.g.files.server.files.model.InternalServerErrorResponseContent;
import com.smithy.g.files.server.files.model.ListCommitsBody;
import com.smithy.g.files.server.files.model.NotFoundErrorResponseContent;
import com.smithy.g.files.server.files.model.UnauthorizedErrorResponseContent;
import com.smithy.g.files.server.files.model.UpdateFileBody;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "v1", description = "the v1 API")
public interface V1Api {

    default V1ApiDelegate getDelegate() {
        return new V1ApiDelegate() {};
    }

    /**
     * GET /v1/repos/{owner}/{repo}/compare/{baseBranch}/{headBranch}
     * Compara dos branches mostrando commits y archivos cambiados. HU-20
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param baseBranch Branch base para comparacion (required)
     * @param headBranch Branch head para comparacion (required)
     * @return CompareCommits 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "compareCommits",
        description = "Compara dos branches mostrando commits y archivos cambiados. HU-20",
        responses = {
            @ApiResponse(responseCode = "200", description = "CompareCommits 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CompareDTO.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/compare/{baseBranch}/{headBranch}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<CompareDTO> compareCommits(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "baseBranch", description = "Branch base para comparacion", required = true, in = ParameterIn.PATH) @PathVariable("baseBranch") String baseBranch,
        @Parameter(name = "headBranch", description = "Branch head para comparacion", required = true, in = ParameterIn.PATH) @PathVariable("headBranch") String headBranch
    ) {
        return getDelegate().compareCommits(owner, repo, baseBranch, headBranch);
    }


    /**
     * PUT /v1/repos/{owner}/{repo}/contents/{filePath+}
     * Sube un archivo al repositorio (create/update por path). RF03.1
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param filePathPlus  (required)
     * @param createFileBody  (required)
     * @return CreateFile 201 response (status code 201)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or ConflictError 409 response (status code 409)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "createFile",
        description = "Sube un archivo al repositorio (create/update por path). RF03.1",
        responses = {
            @ApiResponse(responseCode = "201", description = "CreateFile 201 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FileOperationResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "409", description = "ConflictError 409 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConflictErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    // Mapping defined in V1ApiController due to greedy path handling
    default ResponseEntity<FileOperationResponse> createFile(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        String filePathPlus,
        @Parameter(name = "CreateFileBody", description = "", required = true) @Valid @RequestBody CreateFileBody createFileBody
    ) {
        return getDelegate().createFile(owner, repo, filePathPlus, createFileBody);
    }


    /**
     * POST /v1/repos/{owner}/{repo}/folders
     * Crea una carpeta nueva con .gitkeep. RF03.4
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param createFolderBody  (required)
     * @return CreateFolder 201 response (status code 201)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or ConflictError 409 response (status code 409)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "createFolder",
        description = "Crea una carpeta nueva con .gitkeep. RF03.4",
        responses = {
            @ApiResponse(responseCode = "201", description = "CreateFolder 201 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FileOperationResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "409", description = "ConflictError 409 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConflictErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/repos/{owner}/{repo}/folders",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FileOperationResponse> createFolder(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "CreateFolderBody", description = "", required = true) @Valid @RequestBody CreateFolderBody createFolderBody
    ) {
        return getDelegate().createFolder(owner, repo, createFolderBody);
    }


    /**
     * DELETE /v1/repos/{owner}/{repo}/contents/{filePath+}
     * Elimina un archivo generando un commit de borrado. RF03.5
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param filePathPlus  (required)
     * @param sha SHA del archivo a eliminar (para control de concurrencia) (required)
     * @param message Mensaje del commit (required)
     * @param branch Branch donde eliminar (optional)
     * @return DeleteFile 200 response (status code 200)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "deleteFile",
        description = "Elimina un archivo generando un commit de borrado. RF03.5",
        responses = {
            @ApiResponse(responseCode = "200", description = "DeleteFile 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeleteFileResponseBody.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    // Mapping defined in V1ApiController due to greedy path handling
    default ResponseEntity<DeleteFileResponseBody> deleteFile(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        String filePathPlus,
        @NotNull @Parameter(name = "sha", description = "SHA del archivo a eliminar (para control de concurrencia)", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "sha", required = true) String sha,
        @NotNull @Size(min = 1, max = 500) @Parameter(name = "message", description = "Mensaje del commit", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "message", required = true) String message,
        @Parameter(name = "branch", description = "Branch donde eliminar", in = ParameterIn.QUERY) @Valid @RequestParam(value = "branch", required = false) String branch
    ) {
        return getDelegate().deleteFile(owner, repo, filePathPlus, sha, message, branch);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/commits/{sha}
     * Obtiene el detalle de un commit especifico. HU-18
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param sha  (required)
     * @return GetCommit 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "getCommit",
        description = "Obtiene el detalle de un commit especifico. HU-18",
        responses = {
            @ApiResponse(responseCode = "200", description = "GetCommit 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetCommitBody.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/commits/{sha}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<GetCommitBody> getCommit(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "sha", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sha") String sha
    ) {
        return getDelegate().getCommit(owner, repo, sha);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/commits/{sha}/diff
     * Obtiene el diff de un commit en formato texto. HU-18
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param sha  (required)
     * @return GetCommitDiff 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "getCommitDiff",
        description = "Obtiene el diff de un commit en formato texto. HU-18",
        responses = {
            @ApiResponse(responseCode = "200", description = "GetCommitDiff 200 response", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = ForbiddenErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = NotFoundErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = InternalServerErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/commits/{sha}/diff",
        produces = { "text/plain", "application/json" }
    )
    
    default ResponseEntity<String> getCommitDiff(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "sha", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sha") String sha
    ) {
        return getDelegate().getCommitDiff(owner, repo, sha);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/contents/{filePath+}
     * Obtiene el contenido de un archivo o lista el contenido de un directorio. RF03.3
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param filePathPlus  (required)
     * @param ref Branch, tag o commit SHA (optional)
     * @return GetFileContent 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "getFileContent",
        description = "Obtiene el contenido de un archivo o lista el contenido de un directorio. RF03.3",
        responses = {
            @ApiResponse(responseCode = "200", description = "GetFileContent 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetFileContentBody.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    // Mapping defined in V1ApiController due to greedy path handling
    default ResponseEntity<GetFileContentBody> getFileContent(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        String filePathPlus,
        @Parameter(name = "ref", description = "Branch, tag o commit SHA", in = ParameterIn.QUERY) @Valid @RequestParam(value = "ref", required = false) String ref
    ) {
        return getDelegate().getFileContent(owner, repo, filePathPlus, ref);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/download
     * Descarga un archivo individual del repositorio. RF03.2
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param path  (required)
     * @param ref Branch, tag o commit SHA (optional)
     * @return GetRawFile 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "getRawFile",
        description = "Descarga un archivo individual del repositorio. RF03.2",
        responses = {
            @ApiResponse(responseCode = "200", description = "GetRawFile 200 response", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = byte[].class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = byte[].class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = ForbiddenErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = NotFoundErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = InternalServerErrorResponseContent.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/download",
        produces = { "application/octet-stream", "application/json" }
    )
    
    default ResponseEntity<byte[]> getRawFile(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @NotNull @Parameter(name = "path", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "path", required = true) String path,
        @Parameter(name = "ref", description = "Branch, tag o commit SHA", in = ParameterIn.QUERY) @Valid @RequestParam(value = "ref", required = false) String ref
    ) {
        return getDelegate().getRawFile(owner, repo, path, ref);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/contents
     * Lista el contenido de una ruta del repositorio usando query path. HU-13
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param path Ruta relativa opcional. Si se omite, lista la raiz. (optional)
     * @param ref Branch, tag o commit SHA (optional)
     * @return GetRepositoryContents 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "getRepositoryContents",
        description = "Lista el contenido de una ruta del repositorio usando query path. HU-13",
        responses = {
            @ApiResponse(responseCode = "200", description = "GetRepositoryContents 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetFileContentBody.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/contents",
        produces = { "application/json" }
    )
    
    default ResponseEntity<GetFileContentBody> getRepositoryContents(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "path", description = "Ruta relativa opcional. Si se omite, lista la raiz.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "path", required = false) String path,
        @Parameter(name = "ref", description = "Branch, tag o commit SHA", in = ParameterIn.QUERY) @Valid @RequestParam(value = "ref", required = false) String ref
    ) {
        return getDelegate().getRepositoryContents(owner, repo, path, ref);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/commits
     * Lista el historial de commits del repositorio. HU-18
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param sha Branch o SHA desde donde empezar (optional)
     * @param path Filtrar por path de archivo (optional)
     * @param page  (optional)
     * @param perPage  (optional)
     * @return ListCommits 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "listCommits",
        description = "Lista el historial de commits del repositorio. HU-18",
        responses = {
            @ApiResponse(responseCode = "200", description = "ListCommits 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListCommitsBody.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/commits",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ListCommitsBody> listCommits(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "sha", description = "Branch o SHA desde donde empezar", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sha", required = false) String sha,
        @Parameter(name = "path", description = "Filtrar por path de archivo", in = ParameterIn.QUERY) @Valid @RequestParam(value = "path", required = false) String path,
        @DecimalMin("1") @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) BigDecimal page,
        @DecimalMin("1") @DecimalMax("100") @Parameter(name = "perPage", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "perPage", required = false) BigDecimal perPage
    ) {
        return getDelegate().listCommits(owner, repo, sha, path, page, perPage);
    }


    /**
     * PATCH /v1/repos/{owner}/{repo}/contents/{filePath+}
     * Actualiza un archivo existente en el repositorio. RF03.1
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param filePathPlus  (required)
     * @param updateFileBody  (required)
     * @return UpdateFile 200 response (status code 200)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or ConflictError 409 response (status code 409)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "updateFile",
        description = "Actualiza un archivo existente en el repositorio. RF03.1",
        responses = {
            @ApiResponse(responseCode = "200", description = "UpdateFile 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FileOperationResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "409", description = "ConflictError 409 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConflictErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    // Mapping defined in V1ApiController due to greedy path handling
    default ResponseEntity<FileOperationResponse> updateFile(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        String filePathPlus,
        @Parameter(name = "UpdateFileBody", description = "", required = true) @Valid @RequestBody UpdateFileBody updateFileBody
    ) {
        return getDelegate().updateFile(owner, repo, filePathPlus, updateFileBody);
    }

}
